### ISSUE TITLE
This doesn't work 

### ISSUE THREAD

**Issue by patientplatypus** [eolszewski/ipfs-pubsub-chatroom#2]
After npm i I try npm run build and get the following:

patientplatypus:~/Documents/zennify.me/ipfsEXPERIMENTAL/ipfs-pubsub-chatroom:12:06:39$npm run build

> ipfs-pubsub-chatroom@0.1.0 build /Users/patientplatypus/Documents/zennify.me/ipfsEXPERIMENTAL/ipfs-pubsub-chatroom
> react-scripts build

/Users/patientplatypus/Documents/zennify.me/ipfsEXPERIMENTAL/ipfs-pubsub-chatroom/node_modules/uglifyjs-webpack-plugin/node_modules/schema-utils/dist/validateOptions.js:44
    throw new _ValidationError2.default(ajv.errors, name);
    ^

ValidationError: UglifyJs Plugin Invalid Options

options['compress'] is an invalid additional property
options['mangle'] is an invalid additional property
options['output'] is an invalid additional property

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-pubsub-chatroom@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipfs-pubsub-chatroom@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patientplatypus/.npm/_logs/2018-08-31T17_08_59_088Z-debug.log
patientplatypus:~/Documents/zennify.me/ipfsEXPERIMENTAL/ipfs-pubsub-chatroom:12:08:59$

**Comment by eolszewski** [comment]
Looking into this now.

**Comment by eolszewski** [comment]
Related: https://github.com/ipfs/js-ipfs/issues/1321

**Comment by eolszewski** [comment]
This has been fixed with https://github.com/eolszewski/ipfs-pubsub-chatroom/pull/3

There is an minify failure happening during the build process, but this will not affect the running of the application.

Please do a fresh pull down from master. Delete your yarn.lock, package-lock, and node_modules. then follow the README instructions.

Let me know if this fixes your problem.

**Comment by patientplatypus** [comment]
Ah thanks - it appears to be working now (although strangely - and you mention this - not with Firefox ??? that seems curious). At a guess are the security settings (ie https etc) too stringent?

I'm currently trying to figure out how to get IPFS to work when you set your own swarm address, so if you have any ideas feel free to comment here: https://stackoverflow.com/questions/52130383/ipfs-swarm-address-malformed. Sorry for the tangent, but I'm a little stuck.

Appreciate your responsiveness - cheers pp

**Comment by eolszewski** [comment]
Awesome, I will be losing this in that case.

^ I believe that to be the case, yes :/

Not sure on that one, if you figure it out, I would greatly appreciate a PR adding it :D 

You might be able to ask in a gitter channel, though?

P.S. We are both in Austin, that's kind of cool.
